name: CI

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 9 * * 1,3,5'
  workflow_dispatch:

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install SDKs (Force npmjs.com)
        run: |
          npm install @jadonamite/stacks-core --registry=https://registry.npmjs.org/
          npm install @jadonamite/chessify-sdk --registry=https://registry.npmjs.org/
          npm install @jadonamite/fundxagon-sdk --registry=https://registry.npmjs.org/

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm test --if-present
